name: MistwoodFarming
version: '${version}'
main: me.munchii.mistwoodfarming.MistwoodFarming
api-version: '1.20'
load: STARTUP
depend: [igloolib]
commands:
  shop:
    description: Open the shop
    usage: /shop
