Database:
  Host: localhost
  Port: 5000
  Name: farming
  Username: admin
  Password: pwd
  PlayersCollection: players
  FarmsCollection: farms
  AuthKeysCollection: auth-keys # Change to: none, if you don't use the `DiscordLink` module
  
Modules:
  DiscordLink: true

Fishing:
  PlaySounds: true
