name: igloolib
version: '${version}'
main: me.munchii.igloolib.Igloolib
api-version: '1.20'
load: STARTUP
authors: [munchii]
description: plugin library for spigot/paper
commands:
  igloo:
    description: Main command
    usage: /igloo
    permission: igloolib.admin
  test:
    description: a
    usage: b
