name: Farming
main: net.mistwood.FarmingPlugin.Main
version: 1.0.3
author: Mistwood
commands:
  shop:
    description: Main shop command
    usage: /shop
  farm:
    description: Main farm command
    usage: /farm ? for help
    aliases: [farms, f]
   fishing:
   	description: Main fishing command
   	usage: /fishing ? for help
   	aliases: [fs]
permissions:
  farming.*:
    description: All farming commands
    default: op
    children:
      farming.command.user: true
      farming.command.admin: true
  farming.command.user:
    description: Recommended user permissions
    default: true
    children:
      farming.command.info: true
      farming.command.help: true
      farming.command.add: true
      farming.command.kick: true
      farming.command.promote: true
      farming.command.demote: true
      farming.command.leave: true
      farming.command.accept: true
      farming.command.deny: true
      farming.command.rename: true
  farming.command.admin:
    description: Recommended admin permissions
    default: op
    children:
      farming.command.info: true
      farming.command.help: true
      farming.command.add: true
      farming.command.kick: true
      farming.command.promote: true
      farming.command.demote: true
      farming.command.leave: true
      farming.command.accept: true
      farming.command.deny: true
      farming.command.rename: true
      farming.command.reload: true
